### ISSUE TITLE
Set survey to target recipients

### ISSUE THREAD

**Issue by david90** [skygear-demo/skygear-nps-bot-js#3]
1. At the survey day, send the survey message to all selected members at 10 am local time zone.
2. If answer is not 1-10, reply "Please rate from 1-10"
3. If no respond for 1 day, send again 24 hours later
4. After received correct respond, ask "do you have anything else want to share?"
5. The reply will be recorded, if no reply no follow up is needed.

**Comment by SiuMingCode** [comment]
439a924e2628cae79d32768964c70a61a5fdfaa9
